blank_issues_enabled: false
contact_links:
  - name: Support on Discord
    url: https://discord.com/channels/808476259016769546/964717019289247754
    about: Ask questions directly to our support on discord
